
import { Language } from './types';

export const WALLET_ADDRESS = "0x4ae94eafa539f70223fcbbd15b8e0d0a76991ad6";

export const AD_CONFIG = {
  enabled: true,
  dashboard: {
    show: true,
    title: "🚀 پیشنهاد ویژه: اشتراک طلایی",
    description: "دسترسی نامحدود به هوش مصنوعی و چاپ حرفه‌ای سوالات!",
    buttonText: "ارتقا به VIP",
    action: "settings",
    gradient: "from-indigo-600 to-purple-700",
    icon: "fa-crown"
  }
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fa: {
    'nav.dashboard': 'داشبورد',
    'nav.exam': 'آزمون',
    'nav.flashcards': 'یادگیری هوشمند',
    'nav.bank': 'بانک سوالات',
    'nav.ai': 'طراح هوشمند (AI)',
    'nav.settings': 'تنظیمات',
    'nav.stats': 'گزارش پیشرفت',
    'ai.method.text': 'تبدیل متن 📄',
    'ai.method.topic': 'طراحی موضوعی ✨',
    'ai.method.manual': 'تولید دستی 🛠️',
    'ai.topic': 'موضوع آزمون',
    'ai.count': 'تعداد سوالات',
    'ai.difficulty': 'سطح دشواری',
    'ai.generate': 'شروع جادوی طراحی',
    'ai.manual.step1': '۱. تنظیمات اولیه',
    'ai.manual.step1.desc': 'موضوع و تعداد را مشخص کنید.',
    'ai.manual.step2': '۲. کپی پرامپت طلایی',
    'ai.manual.step2.desc': 'متن تولید شده را کپی کنید.',
    'ai.manual.step3': '۳. هوش مصنوعی خارجی',
    'ai.manual.step3.desc': 'متن را در ChatGPT بفرستید.',
    'ai.manual.step4': '۴. بازگرداندن کد',
    'ai.manual.step4.desc': 'کد دریافتی را اینجا بچسبانید.',
    'ai.manual.copy': 'کپی پرامپت طلایی',
    'ai.manual.import': 'بررسی و استخراج',
    'ai.manual.placeholder': 'کد JSON دریافتی را اینجا بچسبانید...',
    'ai.premium.lock': 'تولید ۵۰ یا ۱۰۰ سوال مخصوص کاربران طلایی است. ارتقا می‌دهید؟ 🔒',
    'common.back': 'بازگشت',
    'common.save': 'ذخیره در بانک',
    'common.cancel': 'انصراف',
    'dash.welcome': 'سلام نابغه! 🚀',
    'settings.darkMode': 'حالت شب/روز'
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.exam': 'Exam',
    'nav.flashcards': 'Flashcards',
    'nav.bank': 'Bank',
    'nav.ai': 'AI Designer',
    'nav.settings': 'Settings',
    'nav.stats': 'Stats',
    'ai.method.text': 'Text to Quiz 📄',
    'ai.method.topic': 'Topic Based ✨',
    'ai.method.manual': 'Manual Mode 🛠️',
    'ai.topic': 'Quiz Topic',
    'ai.count': 'Questions',
    'ai.difficulty': 'Level',
    'ai.generate': 'Start AI Magic',
    'ai.manual.step1': '1. Setup Quiz',
    'ai.manual.step1.desc': 'Set topic and count.',
    'ai.manual.step2': '2. Copy Prompt',
    'ai.manual.step2.desc': 'Copy the golden text.',
    'ai.manual.step3': '3. Use External AI',
    'ai.manual.step3.desc': 'Send to ChatGPT/DeepSeek.',
    'ai.manual.step4': '4. Paste Result',
    'ai.manual.step4.desc': 'Paste the JSON code here.',
    'ai.manual.copy': 'Copy Golden Prompt',
    'ai.manual.import': 'Extract Questions',
    'ai.manual.placeholder': 'Paste received JSON here...',
    'ai.premium.lock': '50/100 questions is for VIP members only. Upgrade? 🔒',
    'common.back': 'Back',
    'common.save': 'Save to Bank',
    'common.cancel': 'Cancel',
    'dash.welcome': 'Hello Genius! 🚀',
    'settings.darkMode': 'Dark Mode'
  },
  ku: {
    'nav.dashboard': 'داشبۆرد',
    'nav.exam': 'تاقیکردنەوە',
    'nav.flashcards': 'فێربوونی زیرەک',
    'nav.bank': 'بانکی پرسیار',
    'nav.ai': 'داڕێژەری زیرەک',
    'nav.settings': 'ڕێکخستنەکان',
    'nav.stats': 'ئامارەکان',
    'ai.method.text': 'گۆڕینی دەق 📄',
    'ai.method.topic': 'دیزاینی بابەت ✨',
    'ai.method.manual': 'دەستی 🛠️',
    'ai.topic': 'بابەتی تاقیکردنەوە',
    'ai.count': 'ژمارەی پرسیار',
    'ai.difficulty': 'ئاستی قورسی',
    'ai.generate': 'دەستپێکردنی جادوو',
    'ai.manual.step1': '١. ڕێکخستنی پرسیار',
    'ai.manual.step2': '٢. کۆپی پڕۆمپت',
    'ai.manual.step3': '٣. زیرەکی دەستکرد',
    'ai.manual.step4': '٤. هێنانەوەی کۆد',
    'ai.manual.copy': 'کۆپی پڕۆمپتی زێڕین',
    'ai.manual.import': 'دەرهێنانی پرسیارەکان',
    'ai.premium.lock': '٥٠ یان ١٠٠ پرسیار بۆ VIPیە. ئەپگرەید دەکەیت؟ 🔒',
    'common.back': 'گەڕانەوە',
    'common.save': 'پاشکەوتکردن',
    'common.cancel': 'پاشگەزبوونەوە',
    'dash.welcome': 'سڵاو بلیمەت! 🚀',
    'settings.darkMode': 'شێوازی شەو'
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.exam': 'الاختبار',
    'nav.flashcards': 'التعلم الذكي',
    'nav.bank': 'بنك الأسئلة',
    'nav.ai': 'المصمم الذكي',
    'nav.settings': 'الإعدادات',
    'nav.stats': 'الإحصائيات',
    'ai.method.text': 'تحويل النص 📄',
    'ai.method.topic': 'تصميم موضوعي ✨',
    'ai.method.manual': 'إنتاج يدوي 🛠️',
    'ai.topic': 'موضوع الاختبار',
    'ai.count': 'عدد الأسئلة',
    'ai.difficulty': 'مستوى الصعوبة',
    'ai.generate': 'بدء السحر',
    'ai.manual.step1': '١. إعداد الاختبار',
    'ai.manual.step2': '٢. نسخ البرومبت',
    'ai.manual.step3': '٣. ذكاء خارجي',
    'ai.manual.step4': '٤. استيراد الكود',
    'ai.manual.copy': 'نسخ البرومبت الذهبي',
    'ai.manual.import': 'استخراج الأسئلة',
    'ai.premium.lock': '٥٠ أو ١٠٠ سؤال للمشتركين فقط. هل تريد الترقية؟ 🔒',
    'common.back': 'رجوع',
    'common.save': 'حفظ في البنك',
    'common.cancel': 'إلغاء',
    'dash.welcome': 'أهلاً بك يا عبقري! 🚀',
    'settings.darkMode': 'الوضع الليلي'
  }
};
