
import { Language } from './types';

export const WALLET_ADDRESS = "0x4ae94eafa539f70223fcbbd15b8e0d0a76991ad6";

export const AD_CONFIG = {
  enabled: true,
  dashboard: {
    show: true,
    title: "🚀 پیشنهاد ویژه: اشتراک طلایی",
    description: "دسترسی نامحدود به هوش مصنوعی و چاپ حرفه‌ای سوالات!",
    buttonText: "ارتقا به VIP",
    action: "settings",
    gradient: "from-indigo-600 to-purple-700",
    icon: "fa-crown"
  }
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  fa: {
    'nav.dashboard': 'داشبورد',
    'nav.exam': 'آزمون',
    'nav.flashcards': 'یادگیری هوشمند',
    'nav.bank': 'بانک سوالات',
    'nav.ai': 'طراح هوشمند (AI)',
    'nav.settings': 'تنظیمات',
    'nav.stats': 'گزارش پیشرفت',
    'ai.method.text': 'تبدیل متن 📄',
    'ai.method.topic': 'طراحی موضوعی ✨',
    'ai.method.manual': 'تولید دستی 🛠️',
    'ai.topic': 'موضوع آزمون',
    'ai.count': 'تعداد سوالات',
    'ai.difficulty': 'سطح دشواری',
    'ai.generate': 'شروع جادوی طراحی',
    'ai.manual.step1': '۱. تنظیمات هوشمند',
    'ai.manual.step1.desc': 'مشخصات سوالات درخواستی خود را وارد کنید.',
    'ai.manual.step2': '۲. کپی پرامپت طلایی',
    'ai.manual.step2.desc': 'این متن را کپی کرده و در ChatGPT یا Claude بفرستید.',
    'ai.manual.step3': '۳. وارد کردن کد نهایی',
    'ai.manual.step3.desc': 'کد JSON دریافتی را در کادر زیر قرار دهید.',
    'ai.manual.copy': 'کپی پرامپت طلایی',
    'ai.manual.import': 'بررسی و استخراج سوالات',
    'ai.manual.placeholder': 'کد JSON را اینجا بچسبانید...',
    'ai.premium.lock': 'انتخاب ۵۰ یا ۱۰۰ سوال مخصوص کاربران طلایی است. مایل به ارتقا هستید؟ 🔒',
    'common.back': 'بازگشت',
    'common.save': 'ذخیره در بانک',
    'common.cancel': 'انصراف',
    'dash.welcome': 'سلام نابغه! 🚀',
    'dash.xp': 'امتیاز تجربه',
    'dash.level': 'سطح فعلی',
    'dash.streak': 'توالی (Streak)',
    'dash.mastery': 'تسلط حافظه',
    'dash.totalCards': 'کل کارت‌ها',
    'dash.due': 'مرور مانده',
    'settings.darkMode': 'حالت شب/روز'
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.exam': 'Exam',
    'nav.flashcards': 'Flashcards',
    'nav.bank': 'Question Bank',
    'nav.ai': 'AI Designer',
    'nav.settings': 'Settings',
    'nav.stats': 'Analytics',
    'ai.method.text': 'Text to Quiz 📄',
    'ai.method.topic': 'Topic Based ✨',
    'ai.method.manual': 'Manual Mode 🛠️',
    'ai.topic': 'Exam Topic',
    'ai.count': 'Question Count',
    'ai.difficulty': 'Difficulty',
    'ai.generate': 'Generate Magic',
    'ai.manual.step1': '1. Prompt Setup',
    'ai.manual.step1.desc': 'Set the parameters for your custom prompt.',
    'ai.manual.step2': '2. Copy Golden Prompt',
    'ai.manual.step2.desc': 'Copy this text and send it to an external AI.',
    'ai.manual.step3': '3. Paste JSON Code',
    'ai.manual.step3.desc': 'Paste the received JSON result here.',
    'ai.manual.copy': 'Copy Golden Prompt',
    'ai.manual.import': 'Extract Questions',
    'ai.manual.placeholder': 'Paste JSON code here...',
    'ai.premium.lock': '50/100 questions is for Gold members. Upgrade now? 🔒',
    'common.back': 'Back',
    'common.save': 'Save to Bank',
    'common.cancel': 'Cancel',
    'dash.welcome': 'Hello Genius! 🚀',
    'dash.xp': 'XP Score',
    'dash.level': 'Level',
    'dash.streak': 'Streak',
    'dash.mastery': 'Mastery',
    'dash.totalCards': 'Total Cards',
    'dash.due': 'Due for Review',
    'settings.darkMode': 'Dark/Light Mode'
  },
  ku: {
    'nav.dashboard': 'داشبۆرد',
    'nav.exam': 'تاقیکردنەوە',
    'nav.flashcards': 'فێربوونی زیرەک',
    'nav.bank': 'بانکی پرسیار',
    'nav.ai': 'داڕێژەری زیرەک',
    'nav.settings': 'ڕێکخستنەکان',
    'nav.stats': 'ئامارەکان',
    'ai.method.text': 'گۆڕینی دەق 📄',
    'ai.method.topic': 'دیزاینی بابەت ✨',
    'ai.method.manual': 'دەستی 🛠️',
    'ai.topic': 'بابەتی تاقیکردنەوە',
    'ai.count': 'ژمارەی پرسیار',
    'ai.difficulty': 'ئاستی قورسی',
    'ai.generate': 'دەستپێکردنی جادوو',
    'ai.manual.step1': '١. ڕێکخستنی پڕۆمپت',
    'ai.manual.step1.desc': 'تایبەتمەندی پرسیارەکان بنووسە.',
    'ai.manual.step2': '٢. کۆپی پڕۆمپتی زێڕین',
    'ai.manual.step2.desc': 'ئەم دەقە کۆپی بکە و بۆ زیرەکی دەستکردی بنێرە.',
    'ai.manual.step3': '٣. هێنانە ناوەوەی کۆد',
    'ai.manual.step3.desc': 'کۆدی JSON لێرە دابنێ.',
    'ai.manual.copy': 'کۆپی پڕۆمپتی زێڕین',
    'ai.manual.import': 'دەرهێنانی پرسیارەکان',
    'ai.manual.placeholder': 'کۆدی JSON لێرە دابنێ...',
    'ai.premium.lock': '٥٠ یان ١٠٠ پرسیار بۆ بەکارهێنەرانی زێڕینە. دەتەوێت ئەپگرەید بکەیت؟ 🔒',
    'common.back': 'گەڕانەوە',
    'common.save': 'پاشکەوتکردن',
    'common.cancel': 'پاشگەزبوونەوە',
    'dash.welcome': 'سڵاو بلیمەت! 🚀',
    'dash.xp': 'خاڵی XP',
    'dash.level': 'ئاست',
    'dash.streak': 'بەردەوامی',
    'dash.mastery': 'زاڵبوون',
    'dash.totalCards': 'کۆی کارتەکان',
    'dash.due': 'ماوە بۆ پێداچوونەوە',
    'settings.darkMode': 'شێوازی شەو/ڕۆژ'
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.exam': 'الاختبار',
    'nav.flashcards': 'التعلم الذكي',
    'nav.bank': 'بنك الأسئلة',
    'nav.ai': 'المصمم الذكي',
    'nav.settings': 'الإعدادات',
    'nav.stats': 'الإحصائيات',
    'ai.method.text': 'تحويل النص 📄',
    'ai.method.topic': 'تصميم موضوعي ✨',
    'ai.method.manual': 'إنتاج يدوي 🛠️',
    'ai.topic': 'موضوع الاختبار',
    'ai.count': 'عدد الأسئلة',
    'ai.difficulty': 'مستوى الصعوبة',
    'ai.generate': 'بدء السحر',
    'ai.manual.step1': '١. إعداد البرومبت',
    'ai.manual.step1.desc': 'أدخل مواصفات الأسئلة المطلوبة.',
    'ai.manual.step2': '٢. نسخ البرومبت الذهبي',
    'ai.manual.step2.desc': 'انسخ هذا النص وأرسله إلى ذكاء اصطناعي خارجي.',
    'ai.manual.step3': '٣. إدراج الكود النهائي',
    'ai.manual.step3.desc': 'ضع كود JSON المستلم في المربع أدناه.',
    'ai.manual.copy': 'نسخ البرومبت الذهبي',
    'ai.manual.import': 'استخراج الأسئلة',
    'ai.manual.placeholder': 'الصق كود JSON هنا...',
    'ai.premium.lock': '٥٠ أو ١٠٠ سؤال للمشتركين الذهبيين. هل تريد الترقية؟ 🔒',
    'common.back': 'رجوع',
    'common.save': 'حفظ في البنك',
    'common.cancel': 'إلغاء',
    'dash.welcome': 'أهلاً بك يا عبقري! 🚀',
    'dash.xp': 'نقاط الخبرة',
    'dash.level': 'المستوى الحالي',
    'dash.streak': 'السلسلة',
    'dash.mastery': 'إتقان الذاكرة',
    'dash.totalCards': 'إجمالي البطاقات',
    'dash.due': 'بانتظار المراجعة',
    'settings.darkMode': 'وضع الليل/النهار'
  }
};
